version: "3.8"

services:
  backend:
    container_name: gt-retail-backend
    image: backend-app-prod
    env_file: env.list
    ports:
      - '8090:8090'
    build:
      context: .
      target: production
    depends_on:
      - database

  frontend:
    container_name: gt-retail-frontend
    image: frontend-app-prod
    ports:
      - '80:80'
    environment:
      API_HOST: gt-retail-backend
      API_PORT: 8090
      WEB_PORT: 80
    build:
      context: webapp
      target: production
    depends_on:
      - backend

  database:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retail