apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gt-retail-backend-vpa-rt
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       gt-retail-backend-rt
  updatePolicy:
    updateMode: "Off"
