apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-rt
spec:
  selector:
    app: gt-retail-frontend-rt
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080