apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-retail-backend-delsin
  labels:
    app: gt-retail-backend-delsin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gt-retail-backend-delsin
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: gt-retail-backend-delsin
    spec:
      containers:
        - name: gt-retail-backend
          image: us-east4-docker.pkg.dev/gt-retail-324419/gtsoftware-repo/gtretail-backend-app:11
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: 8090
            periodSeconds: 60
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: 8090
            periodSeconds: 30
            initialDelaySeconds: 50
          ports:
            - containerPort: 8090
          env:
            - name: APP-NAME
              value: gt-retail-delsin
            - name: PROFILE
              value: prod
            - name: JWT_SIGN_KEY
              valueFrom:
                configMapKeyRef:
                  name: config-delsin
                  key: JWT_SIGN_KEY
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: config-delsin
                  key: DB_URL
            - name: DB_PASSWRD
              valueFrom:
                configMapKeyRef:
                  name: config-delsin
                  key: DB_PASSWRD
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: config-delsin
                  key: DB_USER
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - backend