apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer-delsin
spec:
  selector:
    app: gt-retail-backend-delsin
  ports:
    - protocol: 'TCP'
      port: 8090
      targetPort: 8090
  type: ClusterIP