apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gt-retail-frontend-vpa-delsin
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       gt-retail-frontend-delsin
  updatePolicy:
    updateMode: "Off"
