apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-delsin
spec:
  selector:
    app: gt-retail-frontend-delsin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080