apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-retail-frontend-delsin
  labels:
    app: gt-retail-frontend-delsin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gt-retail-frontend-delsin
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: gt-retail-frontend-delsin
    spec:
      containers:
        - name: gt-retail-frontend
          image: us-east4-docker.pkg.dev/gt-retail-324419/gtsoftware-repo/gtretail-frontend-app:26
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 60
            initialDelaySeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: API_HOST
              value: backend-loadbalancer-delsin.default
            - name: API_PORT
              value: "8090"
            - name: WEB_PORT
              value: "8080"
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 20Mi
      nodeSelector:
        cloud.google.com/gke-spot: "true"